### ISSUE TITLE
how to use?

### ISSUE THREAD

**Issue by dcsan** [types/npm-debug#1]
I usually pass a second param when requiring debug with standard JS projects.
but typestrong (or tslint) is complaining for that:

![image](https://cloud.githubusercontent.com/assets/514002/13450413/ec121b4e-dfe9-11e5-9a21-b4fb581a7336.png)

seems to work when broken across two calls tho:

``` js
import dbg = require("debug");
let debug = dbg("mongo-async-test");
debug("startup");
```

**Comment by blakeembrey** [comment]
As you've discovered, you can't use the `import` construct with chaining. It's a limitation of the TypeScript syntax - legitimate or not. I can't find a logged issue in TypeScript for this, but I'm sure it's intentional. 

The correct workaround is as you've found, import it and then create the debug function.

**Comment by blakeembrey** [comment]
Also, thanks for asking here :smile: How did you manage to get to this repo? Just curious.

**Comment by dcsan** [comment]
thanks for your help. I got here from:

http://stackoverflow.com/questions/35738180/how-to-import-require-standard-node-modules-in-typescript?noredirect=1#comment59150899_35738180
